In [1]:
from scipy.stats import pearsonr
import numpy as np

a = np.array([1,2,3,4,5])
b = a * 3 + 2
b

array([ 5,  8, 11, 14, 17])

In [2]:
pearsonr(a,b)

PearsonRResult(statistic=1.0, pvalue=0.0)

In [3]:
b = a ** 3 + 2
b

array([  3,  10,  29,  66, 127])

In [4]:
pearsonr(a,b)

PearsonRResult(statistic=0.9431175138077006, pvalue=0.016145855288630363)

In [36]:
import pandas as pd
import re as re

file="C:\\Users\\Priscila\\Downloads\\BigmacPrice.csv"
df=pd.read_csv(file)
df.head()

date currency_code       name  local_price  dollar_ex  dollar_price
0  2000-04-01           ARS  Argentina         2.50          1          2.50
1  2000-04-01           AUD  Australia         2.59          1          2.59
2  2000-04-01           BRL     Brazil         2.95          1          2.95
3  2000-04-01           GBP    Britain         1.90          1          1.90
4  2000-04-01           CAD     Canada         2.85          1          2.85

In [45]:
df.corr(numeric_only = True)

local_price  dollar_ex  dollar_price
local_price      1.000000   0.974445      0.001062
dollar_ex        0.974445   1.000000     -0.007300
dollar_price     0.001062  -0.007300      1.000000

In [42]:
from scipy.stats import spearmanr
import numpy as np

a = np.array([1,2,3,4,5])
b = a * 3 + 2
b

array([ 5,  8, 11, 14, 17])

In [43]:
spearmanr(a,b)

SignificanceResult(statistic=0.9999999999999999, pvalue=1.4042654220543672e-24)

In [48]:
b = a ** 3 + 2
b

array([  3,  10,  29,  66, 127])

In [49]:
spearmanr(a,b)

SignificanceResult(statistic=0.9999999999999999, pvalue=1.4042654220543672e-24)

In [47]:
df.corr(method='spearman',numeric_only = True)

local_price  dollar_ex  dollar_price
local_price      1.000000   0.962643     -0.104770
dollar_ex        0.962643   1.000000     -0.335277
dollar_price    -0.104770  -0.335277      1.000000